name: Android CI

on:
  workflow_dispatch:
    inputs:
      release:
        description: "yes to release"
        required: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Kotlin
      uses: fwilhe2/setup-kotlin@0.2.0
      with:
      version: '1.6.10'


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
